version: 2
references:
  # ----------------------------
  # Cache Configuration
  # ----------------------------
  cache_key: &cache_key
    key: cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key
  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      paths:
        - ~/.gradle
        - ~/.m2
# ----------------------------
# Docker Configuration
# ----------------------------
android_config: &android_config
  working_directory: ~/your-project-root
  docker:
    - image: circleci/android:api-27-alpha
  environment:
    TERM: dumb
    ANDROID_SDK_VERSION: 27
    ANDROID_BUILD_TOOLS_VERSION: 27.0.2
    GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2560M -XX:+HeapDumpOnOutOfMemoryError"'
# ----------------------------
# Job Section
# ----------------------------
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "crimson/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "crimson/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: crimson/build/reports
          destination: reports
      - store_test_results:
          path: crimson/build/test-results
# ----------------------------
# Workflows
# ----------------------------
workflows:
  version: 2
  debug_build_deploy:
    jobs:
      - build_debug:
  release_build_deploy:
    jobs:
      - build_release: